name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/DesktopApplicationLauncher.sln
    - name: Build
      run: dotnet build ./src/DesktopApplicationLauncher.sln --no-restore --configuration Release
    - name: Test
      run: ForEach ($folder in (Get-ChildItem -Path test -Directory)) { dotnet test $folder.FullName --no-build --verbosity normal --configuration Release }
